### ISSUE TITLE
[Crash] client crash when start

### ISSUE THREAD

**Issue by SummerXXXX** [SuperMartijn642/ItemCollectors#15]
**Version Info**
- Minecraft  1.19
- Item Collectors 1.1.5-forge-mc1.19
- Forge 41.0.44

**Steps to Reproduce**
... Client crash when click "start game" button

**Crash report (~/logs/latest.log)**
[client crash log](https://gist.github.com/SummerXXXX/02008a566bbbf5bb25f2b4aba06c94c4)
[latest.log](https://github.com/SuperMartijn642/ItemCollectors/files/8945458/latest.log)

**Comment by SuperMartijn642** [comment]
Do you have my core and config libs installed?
![image](https://user-images.githubusercontent.com/12382965/174725009-80633b55-d09c-41c6-816b-8b06e8456fef.png)

I believe this is an issue in Forge currently [#8772](https://github.com/MinecraftForge/MinecraftForge/issues/8772) where it will crash instead of showing a message when a dependency is not installed.

**Comment by SummerXXXX** [comment]
oh, Sorry for mising that, yes you are right, I didn't install the lib, 
Thanks
