### ISSUE TITLE
[Bug] Mod files tagged as compatible with 1.20.4 Neoforge are not

### ISSUE THREAD

**Issue by nanonestor** [SuperMartijn642/ItemCollectors#30]
**Version Info**
- Minecraft 1.20.4
- Modloader - NEOFORGE
- 
- Item Collectors - itemcollectors-1.1.8-forge-mc1.20.jar

**Description of the Bug**
You have tagged this file as compatible with NEOFORGE / Minecraft 1.20.4 but it is not compatible with the dependencies etc entered in your mods.toml.  It makes me wonder if you have actually tested the mod with the changes NEOFORGE has made in newer versions after 1.20.1 as well.  

Time to check over the mods published such as Trashcans, Durability Tooltip, etc as well, as they seem to be in a similar boat.  Thanks.

**Steps to Reproduce**
Attempt to load the above version using Neoforge 1.20.4

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
The files for Item Collectors and some of the other mods you mentioned work for Forge 1.20 - 1.20.4 and NeoForge 1.20.1. With the way CurseForge's and Modrinth's systems work, I cannot mark these files correctly.
I can select what Minecraft versions the file works for and what modloaders the file works for, but I cannot specify different Minecraft versions per modloader.

As NeoForge 1.20.1 was around for a bit, many people are already using these files for NeoForge 1.20.1. Simply unmarking it for NeoForge is thus not an option as modpacks and people's profiles may break.

I want to make dedicated NeoForge versions of my mods anyways which would fix this issue. I have been quite busy with school lately, hence I haven't had the time to do this yet. Especially since I have to update it for around 25 mods 😅

**Comment by nanonestor** [comment]
Understood 😅

While the files may work for the ranges you state - perhaps you could publish the same file multiple times with the mods.toml and Curseforge file tags reflecting the versions with actual compatibility for each modloader.

**Comment by SuperMartijn642** [comment]
Item Collectors is now available for NeoForge on 1.20.3 & 1.20.4. Most of my other mods are also, or will be available in the coming days.
